# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/tazrinkhalid/Coding<3/MustangMobility"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/tazrinkhalid/Coding<3/MustangMobility"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/tazrinkhalid/Coding<3/MustangMobility/CMakeFiles" "/Users/tazrinkhalid/Coding<3/MustangMobility//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/tazrinkhalid/Coding<3/MustangMobility/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Mustang_Mobility

# Build rule for target.
Mustang_Mobility: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Mustang_Mobility
.PHONY : Mustang_Mobility

# fast build rule for target.
Mustang_Mobility/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mustang_Mobility.dir/build.make CMakeFiles/Mustang_Mobility.dir/build
.PHONY : Mustang_Mobility/fast

backend/src/Dijkstra.o: backend/src/Dijkstra.cpp.o
.PHONY : backend/src/Dijkstra.o

# target to build an object file
backend/src/Dijkstra.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mustang_Mobility.dir/build.make CMakeFiles/Mustang_Mobility.dir/backend/src/Dijkstra.cpp.o
.PHONY : backend/src/Dijkstra.cpp.o

backend/src/Dijkstra.i: backend/src/Dijkstra.cpp.i
.PHONY : backend/src/Dijkstra.i

# target to preprocess a source file
backend/src/Dijkstra.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mustang_Mobility.dir/build.make CMakeFiles/Mustang_Mobility.dir/backend/src/Dijkstra.cpp.i
.PHONY : backend/src/Dijkstra.cpp.i

backend/src/Dijkstra.s: backend/src/Dijkstra.cpp.s
.PHONY : backend/src/Dijkstra.s

# target to generate assembly for a file
backend/src/Dijkstra.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mustang_Mobility.dir/build.make CMakeFiles/Mustang_Mobility.dir/backend/src/Dijkstra.cpp.s
.PHONY : backend/src/Dijkstra.cpp.s

backend/src/EntranceNode.o: backend/src/EntranceNode.cpp.o
.PHONY : backend/src/EntranceNode.o

# target to build an object file
backend/src/EntranceNode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mustang_Mobility.dir/build.make CMakeFiles/Mustang_Mobility.dir/backend/src/EntranceNode.cpp.o
.PHONY : backend/src/EntranceNode.cpp.o

backend/src/EntranceNode.i: backend/src/EntranceNode.cpp.i
.PHONY : backend/src/EntranceNode.i

# target to preprocess a source file
backend/src/EntranceNode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mustang_Mobility.dir/build.make CMakeFiles/Mustang_Mobility.dir/backend/src/EntranceNode.cpp.i
.PHONY : backend/src/EntranceNode.cpp.i

backend/src/EntranceNode.s: backend/src/EntranceNode.cpp.s
.PHONY : backend/src/EntranceNode.s

# target to generate assembly for a file
backend/src/EntranceNode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mustang_Mobility.dir/build.make CMakeFiles/Mustang_Mobility.dir/backend/src/EntranceNode.cpp.s
.PHONY : backend/src/EntranceNode.cpp.s

backend/src/Graph.o: backend/src/Graph.cpp.o
.PHONY : backend/src/Graph.o

# target to build an object file
backend/src/Graph.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mustang_Mobility.dir/build.make CMakeFiles/Mustang_Mobility.dir/backend/src/Graph.cpp.o
.PHONY : backend/src/Graph.cpp.o

backend/src/Graph.i: backend/src/Graph.cpp.i
.PHONY : backend/src/Graph.i

# target to preprocess a source file
backend/src/Graph.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mustang_Mobility.dir/build.make CMakeFiles/Mustang_Mobility.dir/backend/src/Graph.cpp.i
.PHONY : backend/src/Graph.cpp.i

backend/src/Graph.s: backend/src/Graph.cpp.s
.PHONY : backend/src/Graph.s

# target to generate assembly for a file
backend/src/Graph.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mustang_Mobility.dir/build.make CMakeFiles/Mustang_Mobility.dir/backend/src/Graph.cpp.s
.PHONY : backend/src/Graph.cpp.s

backend/src/PathEdge.o: backend/src/PathEdge.cpp.o
.PHONY : backend/src/PathEdge.o

# target to build an object file
backend/src/PathEdge.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mustang_Mobility.dir/build.make CMakeFiles/Mustang_Mobility.dir/backend/src/PathEdge.cpp.o
.PHONY : backend/src/PathEdge.cpp.o

backend/src/PathEdge.i: backend/src/PathEdge.cpp.i
.PHONY : backend/src/PathEdge.i

# target to preprocess a source file
backend/src/PathEdge.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mustang_Mobility.dir/build.make CMakeFiles/Mustang_Mobility.dir/backend/src/PathEdge.cpp.i
.PHONY : backend/src/PathEdge.cpp.i

backend/src/PathEdge.s: backend/src/PathEdge.cpp.s
.PHONY : backend/src/PathEdge.s

# target to generate assembly for a file
backend/src/PathEdge.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mustang_Mobility.dir/build.make CMakeFiles/Mustang_Mobility.dir/backend/src/PathEdge.cpp.s
.PHONY : backend/src/PathEdge.cpp.s

backend/src/main.o: backend/src/main.cpp.o
.PHONY : backend/src/main.o

# target to build an object file
backend/src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mustang_Mobility.dir/build.make CMakeFiles/Mustang_Mobility.dir/backend/src/main.cpp.o
.PHONY : backend/src/main.cpp.o

backend/src/main.i: backend/src/main.cpp.i
.PHONY : backend/src/main.i

# target to preprocess a source file
backend/src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mustang_Mobility.dir/build.make CMakeFiles/Mustang_Mobility.dir/backend/src/main.cpp.i
.PHONY : backend/src/main.cpp.i

backend/src/main.s: backend/src/main.cpp.s
.PHONY : backend/src/main.s

# target to generate assembly for a file
backend/src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mustang_Mobility.dir/build.make CMakeFiles/Mustang_Mobility.dir/backend/src/main.cpp.s
.PHONY : backend/src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Mustang_Mobility"
	@echo "... backend/src/Dijkstra.o"
	@echo "... backend/src/Dijkstra.i"
	@echo "... backend/src/Dijkstra.s"
	@echo "... backend/src/EntranceNode.o"
	@echo "... backend/src/EntranceNode.i"
	@echo "... backend/src/EntranceNode.s"
	@echo "... backend/src/Graph.o"
	@echo "... backend/src/Graph.i"
	@echo "... backend/src/Graph.s"
	@echo "... backend/src/PathEdge.o"
	@echo "... backend/src/PathEdge.i"
	@echo "... backend/src/PathEdge.s"
	@echo "... backend/src/main.o"
	@echo "... backend/src/main.i"
	@echo "... backend/src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

